name: Configuration
on:
  push:
    branches:
      - master

jobs:
  update_dns:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update DNS
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/$ZONE/dns_records/import" -H "Authorization: Bearer $TOKEN" --form 'file=@dns.txt' --form 'proxied=$PROXIED'
        env:
          TOKEN: ${{ secrets.apitoken }}
          ZONE: ${{ secrets.zone }}
          PROXIED: true
